project_id = "ikabtkxxjqbonqykzsan"

[functions.daydream-stream]
verify_jwt = false

[functions.daydream-prompt]
verify_jwt = false

[functions.livepeer-clip]
verify_jwt = false

[functions.generate-ticket]
verify_jwt = false

[functions.studio-request-upload]
verify_jwt = false

[functions.studio-asset-status]
verify_jwt = false

[functions.save-clip]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.redeem-ticket]
verify_jwt = false

[functions.generate-transformation]
verify_jwt = false
